# Generated by Django 5.0.6 on 2024-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmessage',
            name='context',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='taskmessage',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
