# Generated by Django 5.0.6 on 2024-08-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_message', '0002_alter_taskmessage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
