# Generated by Django 5.0.6 on 2024-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/v1715765148/taskpilot/ffomfbsj8j1wjaiqi5r5.jpg', upload_to='images/'),
        ),
    ]
