# Generated by Django 5.0.6 on 2024-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/v1715765148/taskpilot/ffomfbsj8j1wjaiqi5r5.jpg>', upload_to='images/'),
        ),
    ]
