# Generated by Django 5.0.6 on 2024-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bios',
            field=models.TextField(blank=True, default='Create A Bios!'),
        ),
    ]
