# Generated by Django 5.0.6 on 2024-06-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/drdelhvyt/image/upload/v1714060667/default_profile_qsg0aq.jpg', upload_to='images/'),
        ),
    ]
