# Generated by Django 3.2.4 on 2024-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_message', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_messages',
            field=models.ManyToManyField(blank=True, to='task_message.TaskMessage'),
        ),
    ]
