# Generated by Django 5.0.6 on 2024-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done')], default='In Progress', max_length=20),
        ),
    ]
