# Generated by Django 3.2.4 on 2024-06-07 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(blank=True)),
                ('declined', models.BooleanField(blank=True)),
                ('title', models.CharField(max_length=30)),
                ('context', models.CharField(max_length=50)),
                ('read_status', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recipient_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.inbox')),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
